swagger: '2.0'
info:
  description: Orders System for Online Shop U.de.A
  version: 1.0.0
  title: Orders System
host: localhost
basePath: /orders
tags:
  - name: orders
    description: Access to Store Orders
paths:
  /orders/order:
    post:
      tags:
        - orders
      summary: Place an order for a product
      description: ''
      operationId: placeOrder
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: order placed for purchasing the product
          required: true
          schema:
            $ref: '#/definitions/Order'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: Invalid Order
  /orders/order/{orderId}:
    get:
      tags:
        - orders
      summary: Find purchase order by ID
      description: >-
        For valid response try integer IDs
      operationId: getOrderById
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ID of order that needs to be fetched
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
    post:
      tags:
        - orders
      summary: Update order by ID
      operationId: updateOrderById
      parameters:
        - name: orderId
          in: path
          description: ID of order that needs to be udpated
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: order placed for purchasing the product
          required: true
          schema:
            $ref: '#/definitions/Order'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
    delete:
      tags:
        - orders
      summary: Delete order by ID
      operationId: deleteOrderById
      parameters:
        - name: orderId
          in: path
          description: ID of order that needs to be deleted
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
  /orders/order/{orderId}/checkout:
    post:
      tags:
        - orders
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: order placed for purchasing the product
          required: true
          schema:
            $ref: '#/definitions/Order'
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid Order

definitions:
  Order:
    type: object
    properties:
      id:
        type: integer
        format: int64      
      products:
        type: array
        items:
          - $ref: '#/definitions/Product'
      shipDate:
        type: string
        format: date-time
      status:
        type: string
        description: Order Status
        enum:
          - placed
          - approved
          - delivered
      complete:
        type: boolean
        default: false
    xml:
      name: Order
  Product:
    type: object
    properties:
      id:
        type: integer
        format: int64      
      quantity:
        type: integer
        format: int32      
    xml:
      name: Order

