info:
    app:
        description: Orders System for Online Shop - University of Antioquia
        name: Orders MicroService
        version: 1.0.0
management:
    endpoints:
        web:
            base-path: /
server:
    port: 8090
    servlet:
        context-path: /orders
spring:
    kafka:
        bootstrap-servers: ${KAFKA_BROKERS}
        consumer:
            auto-offset-reset: latest
            group-id: orders-consumers
            properties:
                spring:
                    json:
                        trusted:
                            packages: sample.kafka
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
#        properties:
#            sasl:
#                jaas:
#                    config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
#                mechanism: SCRAM-SHA-256
#            security:
#                protocol: SASL_SSL
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/orders
        username: root
        password:

topic:
    orders: orders
    inventory: inventory
    payments: payments
    accounting: accounting
    cart: cart

